require('dotenv').config();
const path = require('path');
const express = require('express');
const jwt = require('jsonwebtoken');
const { connectDb, getDbStatus, collections, ensureUser, addXp, logAudit, recordGame, unlockAchievement } = require('./db');

const app = express();
const port = process.env.PORT || 3000;
const jwtSecret = process.env.JWT_SECRET || 'local-development-secret';
const users = () => collections.users; const items = () => collections.items; const inventory = () => collections.inventory; const gameStats = () => collections.game_stats; const achievements = () => collections.achievements; const promos = () => collections.promocodes;
const rarities = ['common', 'uncommon', 'rare', 'epic', 'legendary'];
const redNumbers = new Set([1, 3, 5, 7, 9, 12, 14, 16, 18, 19, 21, 23, 25, 27, 30, 32, 34, 36]);
const rouletteColor = number => number === 0 ? 'green' : redNumbers.has(number) ? 'red' : 'black';
const activityTwentyOne = new Map(); const crashSessions = new Map(); let rouletteRound = null;

app.use(express.json());
app.use('/activity/sdk', express.static(path.join(__dirname, '..', 'node_modules', '@discord', 'embedded-app-sdk', 'output')));
app.get('/', (req, res) => res.sendFile(path.join(__dirname, '..', 'public', 'activity', 'index.html')));
app.get('/admin/', (req, res) => res.sendFile(path.join(__dirname, '..', 'public', 'index.html')));
app.use(express.static(path.join(__dirname, '..', 'public')));

const auth = (req, res, next) => { try { req.admin = jwt.verify((req.headers.authorization || '').replace('Bearer ', ''), jwtSecret); if (req.admin.role !== 'admin') throw new Error('Invalid role'); next(); } catch { res.status(401).json({ error: 'Требуется авторизация' }); } };
const activityAuth = (req, res, next) => { try { req.activity = jwt.verify((req.headers.authorization || '').replace('Bearer ', ''), jwtSecret); if (!req.activity.discordId) throw new Error('Invalid token'); next(); } catch { res.status(401).json({ error: 'Требуется авторизация в Discord Activity' }); } };
const activityDeck = () => Array.from({ length: 4 }, () => ['A', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K']).flat().sort(() => Math.random() - .5);
const activityHandValue = cards => { let total = cards.reduce((sum, card) => sum + (card === 'A' ? 11 : ['J', 'Q', 'K'].includes(card) ? 10 : Number(card)), 0), aces = cards.filter(card => card === 'A').length; while (total > 21 && aces--) total -= 10; return total; };
const activityUser = async req => ensureUser(req.activity.discordId, req.activity.username);
const publicUser = user => ({ id: user.id, username: user.username, balance: user.balance });
async function debit(user, amount) { const result = await users().updateOne({ _id: user.id, balance: { $gte: amount } }, { $inc: { balance: -amount } }); if (!result.modifiedCount) throw new Error('Ставка больше баланса.'); }
async function payout(userId, game, bet, amount) { if (amount) await users().updateOne({ _id: userId }, { $inc: { balance: amount } }); await recordGame(userId, game, bet, amount); if (amount > bet) await addXp(userId, 15); await checkAchievements(userId); }
const achievementNames = { first_game: 'Первая игра', high_roller: 'Крупная ставка', first_purchase: 'Первая покупка', daily_week: 'Неделя наград', level_five: 'Пятый уровень' };
async function checkAchievements(userId) { const user = await users().findOne({ _id: userId }); const [games] = await gameStats().aggregate([{ $match: { user_id: userId } }, { $group: { _id: null, total: { $sum: '$played' }, wagered: { $max: '$wagered' } } }]); const [owned] = await inventory().aggregate([{ $match: { user_id: userId } }, { $group: { _id: null, total: { $sum: '$quantity' } } }]); const unlocked = []; for (const [code, condition] of Object.entries({ first_game: (games?.total || 0) >= 1, high_roller: (games?.wagered || 0) >= 1000, first_purchase: (owned?.total || 0) >= 1, daily_week: user.daily_streak >= 7, level_five: user.level >= 5 })) if (condition && await unlockAchievement(userId, code)) unlocked.push(achievementNames[code]); return unlocked; }
async function gameResult(user, game, bet, amount, result) { await debit(user, bet); await payout(user.id, game, bet, amount); const updated = await users().findOne({ _id: user.id }); return { text: result, balance: updated.balance }; }

app.post('/api/login', (req, res) => { if (!process.env.ADMIN_PASSWORD || req.body.password !== process.env.ADMIN_PASSWORD) return res.status(401).json({ error: 'Неверный пароль' }); res.json({ token: jwt.sign({ role: 'admin' }, jwtSecret, { expiresIn: '12h' }) }); });
app.get('/api/activity/config', (req, res) => res.json({ clientId: process.env.CLIENT_ID || '' }));
app.post('/api/activity/token', async (req, res, next) => { try { if (!process.env.CLIENT_ID || !process.env.DISCORD_CLIENT_SECRET || !req.body.code) return res.status(503).json({ error: 'Activity OAuth не настроен.' }); const tokenResponse = await fetch('https://discord.com/api/oauth2/token', { method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams({ client_id: process.env.CLIENT_ID, client_secret: process.env.DISCORD_CLIENT_SECRET, grant_type: 'authorization_code', code: req.body.code }) }); const tokens = await tokenResponse.json(); if (!tokenResponse.ok || !tokens.access_token) return res.status(401).json({ error: 'Discord не подтвердил авторизацию.' }); const profileResponse = await fetch('https://discord.com/api/v10/users/@me', { headers: { Authorization: `Bearer ${tokens.access_token}` } }); const profile = await profileResponse.json(); if (!profileResponse.ok || !profile.id) return res.status(401).json({ error: 'Не удалось получить профиль Discord.' }); const username = profile.global_name || profile.username; await ensureUser(profile.id, username); res.json({ access_token: tokens.access_token, activity_token: jwt.sign({ discordId: profile.id, username }, jwtSecret, { expiresIn: '2h' }) }); } catch (error) { next(error); } });
app.get('/api/activity/me', activityAuth, async (req, res, next) => { try { res.json(publicUser(await activityUser(req))); } catch (error) { next(error); } });
app.post('/api/activity/play', activityAuth, async (req, res, next) => { try { const bet = Number(req.body.bet), game = req.body.game; if (!Number.isInteger(bet) || bet < 1 || !['coin', 'dice', 'slots'].includes(game)) return res.status(400).json({ error: 'Неверные параметры игры.' }); const user = await activityUser(req); let amount = 0, result = ''; if (game === 'coin') { const side = req.body.choice === 'tails' ? 'tails' : 'heads', roll = Math.random() < .5 ? 'heads' : 'tails'; amount = side === roll ? bet * 2 : 0; result = `Выпало ${roll === 'heads' ? 'орёл' : 'решка'}.`; } else if (game === 'dice') { const roll = Math.floor(Math.random() * 6) + 1; amount = roll >= 4 ? bet * 2 : 0; result = `Кубик: ${roll}.`; } else { const icons = ['CHERRY', 'LEMON', 'GEM', '7'], roll = Array.from({ length: 3 }, () => icons[Math.floor(Math.random() * icons.length)]); amount = roll[0] === roll[1] && roll[1] === roll[2] ? bet * (roll[0] === '7' ? 10 : 4) : new Set(roll).size < 3 ? bet * 2 : 0; result = roll.join(' / '); } res.json(await gameResult(user, game, bet, amount, result)); } catch (error) { next(error); } });
app.post('/api/activity/twenty-one/start', activityAuth, async (req, res, next) => { try { const bet = Number(req.body.bet), user = await activityUser(req); if (!Number.isInteger(bet) || bet < 1) throw new Error('Укажи целую ставку.'); await debit(user, bet); const deck = activityDeck(), session = { userId: user.id, bet, deck, player: [deck.pop(), deck.pop()], bot: [deck.pop(), deck.pop()] }, id = Math.random().toString(36).slice(2, 12); activityTwentyOne.set(id, session); res.json({ id, player: session.player, bot: [session.bot[0]], score: activityHandValue(session.player), bet }); } catch (error) { next(error); } });
app.post('/api/activity/twenty-one/:id', activityAuth, async (req, res, next) => { try { const session = activityTwentyOne.get(req.params.id); if (!session || session.userId !== req.activity.discordId) return res.status(404).json({ error: 'Раунд истёк. Начни новую игру.' }); const user = await activityUser(req); if (req.body.action === 'hit') { session.player.push(session.deck.pop()); if (activityHandValue(session.player) <= 21) return res.json({ active: true, player: session.player, bot: [session.bot[0]], score: activityHandValue(session.player), bet: session.bet }); } while (activityHandValue(session.bot) < 17) session.bot.push(session.deck.pop()); const playerScore = activityHandValue(session.player), botScore = activityHandValue(session.bot), won = playerScore <= 21 && (botScore > 21 || playerScore > botScore), draw = playerScore <= 21 && playerScore === botScore, amount = won ? session.bet * 2 : draw ? session.bet : 0, text = playerScore > 21 ? `Перебор: ${playerScore}.` : botScore > 21 ? 'У бота перебор.' : draw ? 'Ничья.' : won ? 'Ты выиграл.' : 'Бот выиграл.'; await payout(user.id, 'twenty-one', session.bet, amount); activityTwentyOne.delete(req.params.id); const updated = await users().findOne({ _id: user.id }); res.json({ active: false, player: session.player, bot: session.bot, score: playerScore, botScore, bet: session.bet, text, balance: updated.balance }); } catch (error) { next(error); } });

function crashMultiplier(session) { return Math.max(1, Math.exp((Date.now() - session.startedAt) / 8500)); }
app.post('/api/activity/crash/start', activityAuth, async (req, res, next) => { try { const bet = Number(req.body.bet), user = await activityUser(req); if (!Number.isInteger(bet) || bet < 1) throw new Error('Укажи целую ставку.'); await debit(user, bet); const id = Math.random().toString(36).slice(2, 12), crashAt = 1.08 + Math.pow(Math.random(), 2.2) * 8, startedAt = Date.now(); const session = { userId: user.id, bet, startedAt, crashAt, crashed: false, settled: false }; crashSessions.set(id, session); setTimeout(async () => { if (crashSessions.get(id) === session && !session.settled) { session.crashed = true; session.settled = true; await payout(user.id, 'crash', bet, 0); } }, Math.ceil(Math.log(crashAt) * 8500) + 100); setTimeout(() => { if (crashSessions.get(id) === session) crashSessions.delete(id); }, 120000); res.json({ id, bet, startedAt }); } catch (error) { next(error); } });
app.get('/api/activity/crash/:id', activityAuth, async (req, res, next) => { try { const session = crashSessions.get(req.params.id); if (!session || session.userId !== req.activity.discordId) return res.status(404).json({ error: 'Раунд истёк.' }); res.json(session.crashed ? { active: false, crashed: true, crashAt: session.crashAt } : { active: true }); } catch (error) { next(error); } });
app.post('/api/activity/crash/:id/cashout', activityAuth, async (req, res, next) => { try { const session = crashSessions.get(req.params.id); if (!session || session.userId !== req.activity.discordId) return res.status(404).json({ error: 'Раунд истёк.' }); const user = await activityUser(req); if (session.crashed || crashMultiplier(session) >= session.crashAt) { if (!session.settled) { session.crashed = true; session.settled = true; await payout(user.id, 'crash', session.bet, 0); } return res.json({ crashed: true, crashAt: session.crashAt, balance: (await users().findOne({ _id: user.id })).balance }); } session.settled = true; const multiplier = crashMultiplier(session), amount = Math.floor(session.bet * multiplier); await payout(user.id, 'crash', session.bet, amount); crashSessions.delete(req.params.id); res.json({ crashed: false, multiplier, amount, balance: (await users().findOne({ _id: user.id })).balance }); } catch (error) { next(error); } });

function rouletteView() { if (!rouletteRound) return { status: 'idle', players: [] }; const { closesAt, players, result } = rouletteRound; return { id: rouletteRound.id, status: result == null ? 'betting' : 'settled', closesAt, result, players: players.map(player => ({ username: player.username, bet: player.bet, choice: player.choice, won: player.won, amount: player.amount })) }; }
async function settleRoulette(round) { if (!round || round.result != null) return; round.result = Math.floor(Math.random() * 37); const color = rouletteColor(round.result); await Promise.all(round.players.map(async player => { const won = player.choice === String(round.result) || player.choice === color; const multiplier = player.choice === String(round.result) ? 36 : player.choice === 'green' ? 14 : 2; player.won = won; player.amount = won ? player.bet * multiplier : 0; await payout(player.userId, 'roulette', player.bet, player.amount); })); setTimeout(() => { if (rouletteRound === round) rouletteRound = null; }, 10000); }
app.get('/api/activity/roulette', activityAuth, (req, res) => res.json(rouletteView()));
app.post('/api/activity/roulette/bet', activityAuth, async (req, res, next) => { try { const bet = Number(req.body.bet), choice = String(req.body.choice); if (!Number.isInteger(bet) || bet < 1 || ![...Array(37).keys()].map(String).includes(choice) && !['red', 'black', 'green'].includes(choice)) throw new Error('Выбери поле рулетки и целую ставку.'); const user = await activityUser(req); if (!rouletteRound || rouletteRound.result != null || Date.now() >= rouletteRound.closesAt) { const round = { id: Math.random().toString(36).slice(2, 10), closesAt: Date.now() + 12000, players: [], result: null }; rouletteRound = round; setTimeout(() => settleRoulette(round).catch(console.error), 12050); } if (rouletteRound.players.some(player => player.userId === user.id)) throw new Error('Ты уже поставил в этом раунде.'); await debit(user, bet); rouletteRound.players.push({ userId: user.id, username: user.username, bet, choice }); res.json({ ...rouletteView(), balance: (await users().findOne({ _id: user.id })).balance }); } catch (error) { next(error); } });

const validDrops = async drops => { if (!Array.isArray(drops) || !drops.length) throw new Error('Кейс должен содержать хотя бы один дроп'); const normalized = drops.map(drop => ({ itemId: Number(drop.itemId), weight: Number(drop.weight), quantity: Number(drop.quantity) })); if (normalized.some(drop => !Number.isInteger(drop.itemId) || !Number.isFinite(drop.weight) || drop.weight <= 0 || !Number.isInteger(drop.quantity) || drop.quantity < 1)) throw new Error('Неверные дропы кейса'); if ((await items().find({ id: { $in: normalized.map(drop => drop.itemId) } })).length !== new Set(normalized.map(drop => drop.itemId)).size) throw new Error('Один или несколько предметов дропа не найдены'); return normalized; };
const addItem = (userId, itemId, quantity) => inventory().updateOne({ user_id: userId, item_id: itemId }, { $inc: { quantity }, $setOnInsert: { _id: `${userId}:${itemId}`, user_id: userId, item_id: itemId } }, { upsert: true });
app.get('/api/health', (req, res) => { const mongo = getDbStatus(); res.status(mongo.connected ? 200 : 503).json({ ok: mongo.connected, mongo }); });
app.get('/api/stats', auth, async (req, res, next) => { try { const [stats] = await users().aggregate([{ $group: { _id: null, users: { $sum: 1 }, balance: { $sum: '$balance' }, level: { $avg: '$level' } } }]); const [purchases] = await inventory().aggregate([{ $group: { _id: null, total: { $sum: '$quantity' } } }]); res.json({ users: stats?.users || 0, balance: stats?.balance || 0, averageLevel: Number(stats?.level || 0).toFixed(1), purchases: purchases?.total || 0 }); } catch (error) { next(error); } });
app.get('/api/users', auth, async (req, res, next) => { try { res.json(await users().find({}, { sort: { balance: -1 }, limit: 100, projection: { _id: 0 } })); } catch (error) { next(error); } });
app.post('/api/users/:id/balance', auth, async (req, res, next) => { try { const amount = Number(req.body.amount); if (!Number.isInteger(amount) || amount === 0) return res.status(400).json({ error: 'Укажи целое ненулевое количество монет' }); await ensureUser(req.params.id, req.body.username || 'Unknown'); await users().updateOne({ _id: req.params.id }, [{ $set: { balance: { $max: [0, { $add: ['$balance', amount] }] } } }]); await logAudit('balance_adjustment', req.params.id, amount, 'Админ-панель'); res.json(await users().findOne({ _id: req.params.id }, { projection: { _id: 0 } })); } catch (error) { next(error); } });
app.post('/api/users/:id/items', auth, async (req, res, next) => { try { const itemId = Number(req.body.itemId), quantity = Number(req.body.quantity); if (!Number.isInteger(itemId) || !Number.isInteger(quantity) || quantity <= 0) return res.status(400).json({ error: 'Неверный предмет или количество' }); if (!await items().findOne({ id: itemId })) return res.status(404).json({ error: 'Предмет не найден' }); await ensureUser(req.params.id, req.body.username || 'Unknown'); await addItem(req.params.id, itemId, quantity); await logAudit('item_grant', req.params.id, quantity, `Предмет #${itemId}`); res.json({ ok: true }); } catch (error) { next(error); } });
app.get('/api/items', auth, async (req, res, next) => { try { res.json(await items().find({}, { sort: { active: -1, id: -1 }, projection: { _id: 0 } })); } catch (error) { next(error); } });
app.post('/api/items', auth, async (req, res) => { try { const { name, description = '', price = 0, icon = '◆', stock = -1, rarity = 'common', type = 'item' } = req.body; if (!name || !rarities.includes(rarity) || !['item', 'case'].includes(type)) throw new Error('Неверные данные предмета'); const item = { name, description, price: Number(price), icon, stock: Number(stock), active: 1, rarity, type }; if (!Number.isFinite(item.price) || !Number.isInteger(item.stock)) throw new Error('Неверная цена или остаток'); if (type === 'case') item.caseDrops = await validDrops(req.body.caseDrops); await items().insertOne(item); res.json({ ...item, _id: undefined }); } catch (error) { res.status(400).json({ error: error.message }); } });
app.patch('/api/items/:id', auth, async (req, res) => { try { const current = await items().findOne({ id: Number(req.params.id) }); if (!current) return res.status(404).json({ error: 'Предмет не найден' }); const update = {}; for (const key of ['name', 'description', 'price', 'icon', 'stock', 'active']) if (req.body[key] !== undefined) update[key] = req.body[key]; if (req.body.rarity !== undefined) { if (!rarities.includes(req.body.rarity)) throw new Error('Неверная редкость'); update.rarity = req.body.rarity; } if (req.body.type !== undefined) { if (!['item', 'case'].includes(req.body.type)) throw new Error('Неверный тип'); update.type = req.body.type; } const type = update.type || current.type || 'item'; if (req.body.caseDrops !== undefined) update.caseDrops = await validDrops(req.body.caseDrops); if (type === 'case' && !update.caseDrops && !(current.caseDrops || []).length) throw new Error('Кейс должен содержать дропы'); if (type !== 'case') update.caseDrops = []; await items().updateOne({ id: current.id }, { $set: update }); res.json(await items().findOne({ id: current.id }, { projection: { _id: 0 } })); } catch (error) { res.status(400).json({ error: error.message }); } });
app.delete('/api/items/:id', auth, async (req, res, next) => { try { await items().deleteOne({ id: Number(req.params.id) }); res.json({ ok: true }); } catch (error) { next(error); } });
app.get('/api/audit', auth, async (req, res, next) => { try { res.json(await collections.audit_log.find({}, { sort: { id: -1 }, limit: 100, projection: { _id: 0 } })); } catch (error) { next(error); } });
app.post('/api/promocodes', auth, async (req, res, next) => { try { const code = String(req.body.code || '').trim().toUpperCase(), reward = Number(req.body.reward), maxUses = Number(req.body.maxUses || 1); if (!/^[A-Z0-9_-]{3,32}$/.test(code) || !Number.isInteger(reward) || reward < 1 || !Number.isInteger(maxUses) || maxUses < 1) return res.status(400).json({ error: 'Неверные данные промокода' }); await promos().insertOne({ _id: code, code, reward, max_uses: maxUses, uses: 0, active: 1, expires_at: null }); await logAudit('promocode_create', null, reward, code); res.json({ ok: true }); } catch (error) { next(error); } });
app.use((error, req, res, next) => { console.error(error); res.status(500).json({ error: error.message || 'Внутренняя ошибка сервера' }); });
function connectMongoWithRetry() { connectDb().then(() => console.log('MongoDB connected')).catch(error => { console.error('MongoDB connection failed, retrying in 30 seconds:', error.message); setTimeout(connectMongoWithRetry, 30000); }); }
function start() { app.listen(port, () => console.log(`Activity: http://localhost:${port} · Admin panel: http://localhost:${port}/admin/`)); connectMongoWithRetry(); }
start();
