require('dotenv').config();
const path = require('path');
const express = require('express');
const jwt = require('jsonwebtoken');
const { Client, GatewayIntentBits, REST, Routes, SlashCommandBuilder, ActionRowBuilder, ButtonBuilder, ButtonStyle, ModalBuilder, TextInputBuilder, TextInputStyle } = require('discord.js');
const { connectDb, getDbStatus, collections, ensureUser, addXp, logAudit, recordGame, unlockAchievement } = require('./db');

const app = express(); const port = process.env.PORT || 3000; const jwtSecret = process.env.JWT_SECRET || 'local-development-secret';
const users = () => collections.users; const items = () => collections.items; const inventory = () => collections.inventory; const gameStats = () => collections.game_stats; const achievements = () => collections.achievements; const promos = () => collections.promocodes; const claims = () => collections.promo_claims; const auctions = () => collections.auctions;
const rarities = ['common', 'uncommon', 'rare', 'epic', 'legendary'];
app.use(express.json()); app.use(express.static(path.join(__dirname, '..', 'public')));
const auth = (req, res, next) => { try { req.admin = jwt.verify((req.headers.authorization || '').replace('Bearer ', ''), jwtSecret); next(); } catch { res.status(401).json({ error: 'Требуется авторизация' }); } };
const validDrops = async drops => {
  if (!Array.isArray(drops) || !drops.length) throw new Error('Кейс должен содержать хотя бы один дроп');
  const normalized = drops.map(drop => ({ itemId: Number(drop.itemId), weight: Number(drop.weight), quantity: Number(drop.quantity) }));
  if (normalized.some(drop => !Number.isInteger(drop.itemId) || !Number.isFinite(drop.weight) || drop.weight <= 0 || !Number.isInteger(drop.quantity) || drop.quantity < 1)) throw new Error('Неверные дропы кейса');
  if ((await items().find({ id: { $in: normalized.map(drop => drop.itemId) } })).length !== new Set(normalized.map(drop => drop.itemId)).size) throw new Error('Один или несколько предметов дропа не найдены');
  return normalized;
};
app.post('/api/login', (req, res) => { if (!process.env.ADMIN_PASSWORD || req.body.password !== process.env.ADMIN_PASSWORD) return res.status(401).json({ error: 'Неверный пароль' }); res.json({ token: jwt.sign({ role: 'admin' }, jwtSecret, { expiresIn: '12h' }) }); });
app.get('/api/health', (req, res) => { const mongo = getDbStatus(); res.status(mongo.connected ? 200 : 503).json({ ok: mongo.connected, mongo }); });
app.get('/api/stats', auth, async (req, res, next) => { try { const [stats] = await users().aggregate([{ $group: { _id: null, users: { $sum: 1 }, balance: { $sum: '$balance' }, level: { $avg: '$level' } } }]); const [purchases] = await inventory().aggregate([{ $group: { _id: null, total: { $sum: '$quantity' } } }]); res.json({ users: stats?.users || 0, balance: stats?.balance || 0, averageLevel: Number(stats?.level || 0).toFixed(1), purchases: purchases?.total || 0 }); } catch (error) { next(error); } });
app.get('/api/users', auth, async (req, res, next) => { try { res.json(await users().find({}, { sort: { balance: -1 }, limit: 100, projection: { _id: 0 } })); } catch (error) { next(error); } });
app.post('/api/users/:id/balance', auth, async (req, res, next) => { try { const amount = Number(req.body.amount); if (!Number.isInteger(amount) || amount === 0) return res.status(400).json({ error: 'Укажи целое ненулевое количество монет' }); await ensureUser(req.params.id, req.body.username || 'Unknown'); await users().updateOne({ _id: req.params.id }, [{ $set: { balance: { $max: [0, { $add: ['$balance', amount] }] } } }]); await logAudit('balance_adjustment', req.params.id, amount, 'Админ-панель'); res.json(await users().findOne({ _id: req.params.id }, { projection: { _id: 0 } })); } catch (error) { next(error); } });
app.post('/api/users/:id/items', auth, async (req, res, next) => { try { const itemId = Number(req.body.itemId), quantity = Number(req.body.quantity); if (!Number.isInteger(itemId) || !Number.isInteger(quantity) || quantity <= 0) return res.status(400).json({ error: 'Неверный предмет или количество' }); if (!await items().findOne({ id: itemId })) return res.status(404).json({ error: 'Предмет не найден' }); await ensureUser(req.params.id, req.body.username || 'Unknown'); await addItem(req.params.id, itemId, quantity); await logAudit('item_grant', req.params.id, quantity, `Предмет #${itemId}`); res.json({ ok: true }); } catch (error) { next(error); } });
app.get('/api/items', auth, async (req, res, next) => { try { res.json(await items().find({}, { sort: { active: -1, id: -1 }, projection: { _id: 0 } })); } catch (error) { next(error); } });
app.post('/api/items', auth, async (req, res, next) => { try { const { name, description = '', price = 0, icon = '◆', stock = -1, rarity = 'common', type = 'item' } = req.body; if (!name || !rarities.includes(rarity) || !['item', 'case'].includes(type)) return res.status(400).json({ error: 'Неверные данные предмета' }); const item = { name, description, price: Number(price), icon, stock: Number(stock), active: 1, rarity, type }; if (!Number.isFinite(item.price) || !Number.isInteger(item.stock)) return res.status(400).json({ error: 'Неверная цена или остаток' }); if (type === 'case') item.caseDrops = await validDrops(req.body.caseDrops); await items().insertOne(item); res.json({ ...item, _id: undefined }); } catch (error) { res.status(400).json({ error: error.message }); } });
app.patch('/api/items/:id', auth, async (req, res, next) => { try { const current = await items().findOne({ id: Number(req.params.id) }); if (!current) return res.status(404).json({ error: 'Предмет не найден' }); const update = {}; for (const key of ['name', 'description', 'price', 'icon', 'stock', 'active']) if (req.body[key] !== undefined) update[key] = req.body[key]; if (req.body.rarity !== undefined) { if (!rarities.includes(req.body.rarity)) throw new Error('Неверная редкость'); update.rarity = req.body.rarity; } if (req.body.type !== undefined) { if (!['item', 'case'].includes(req.body.type)) throw new Error('Неверный тип'); update.type = req.body.type; } const type = update.type || current.type || 'item'; if (req.body.caseDrops !== undefined) update.caseDrops = await validDrops(req.body.caseDrops); if (type === 'case' && !update.caseDrops && !(current.caseDrops || []).length) throw new Error('Кейс должен содержать дропы'); if (type !== 'case') update.caseDrops = []; await items().updateOne({ id: current.id }, { $set: update }); res.json(await items().findOne({ id: current.id }, { projection: { _id: 0 } })); } catch (error) { res.status(400).json({ error: error.message }); } });
app.delete('/api/items/:id', auth, async (req, res, next) => { try { await items().deleteOne({ id: Number(req.params.id) }); res.json({ ok: true }); } catch (error) { next(error); } });
app.get('/api/audit', auth, async (req, res, next) => { try { res.json(await collections.audit_log.find({}, { sort: { id: -1 }, limit: 100, projection: { _id: 0 } })); } catch (error) { next(error); } });
app.post('/api/promocodes', auth, async (req, res, next) => { try { const code = String(req.body.code || '').trim().toUpperCase(), reward = Number(req.body.reward), maxUses = Number(req.body.maxUses || 1); if (!/^[A-Z0-9_-]{3,32}$/.test(code) || !Number.isInteger(reward) || reward < 1 || !Number.isInteger(maxUses) || maxUses < 1) return res.status(400).json({ error: 'Неверные данные промокода' }); await promos().insertOne({ _id: code, code, reward, max_uses: maxUses, uses: 0, active: 1, expires_at: null }); await logAudit('promocode_create', null, reward, code); res.json({ ok: true }); } catch (error) { next(error); } });
app.use((error, req, res, next) => { console.error(error); res.status(500).json({ error: 'Внутренняя ошибка сервера' }); });

const command = (name, description) => new SlashCommandBuilder().setName(name).setDescription(description);
const commands = [command('balance', 'Показать баланс и уровень'), command('daily', 'Получить ежедневную награду'), command('shop', 'Открыть магазин предметов'), command('buy', 'Купить предмет').addIntegerOption(o => o.setName('item_id').setDescription('ID предмета').setRequired(true)), command('inventory', 'Показать инвентарь'), command('menu', 'Открыть игровое меню'), command('achievements', 'Показать достижения').addUserOption(o => o.setName('user').setDescription('Участник')), command('open-case', 'Открыть свой кейс').addIntegerOption(o => o.setName('item_id').setDescription('ID кейса').setRequired(true)), command('capitalization', 'Показать общую капитализацию сервера'), command('roulette', 'Открыть рулетку').addIntegerOption(o => o.setName('bet').setDescription('Размер ставки').setMinValue(1).setRequired(true)), command('profile', 'Показать игровой профиль').addUserOption(o => o.setName('user').setDescription('Участник')), command('leaderboard', 'Показать рейтинг').addStringOption(o => o.setName('type').setDescription('Рейтинг').addChoices({ name: 'Богатство', value: 'balance' }, { name: 'Уровень', value: 'level' }, { name: 'Игры', value: 'games' })), command('transfer', 'Передать монеты').addUserOption(o => o.setName('user').setDescription('Получатель').setRequired(true)).addIntegerOption(o => o.setName('amount').setDescription('Сумма').setMinValue(1).setRequired(true)), command('weekly', 'Получить еженедельную награду'), command('promo', 'Активировать промокод').addStringOption(o => o.setName('code').setDescription('Код').setRequired(true)), command('coin', 'Монетка').addIntegerOption(o => o.setName('bet').setDescription('Ставка').setMinValue(1).setRequired(true)), command('dice', 'Кости').addIntegerOption(o => o.setName('bet').setDescription('Ставка').setMinValue(1).setRequired(true)), command('slots', 'Слоты').addIntegerOption(o => o.setName('bet').setDescription('Ставка').setMinValue(1).setRequired(true)), command('sell', 'Продать предмет боту').addIntegerOption(o => o.setName('item_id').setDescription('ID предмета').setRequired(true)).addIntegerOption(o => o.setName('quantity').setDescription('Количество').setMinValue(1).setRequired(true)), command('auction-create', 'Выставить предмет').addIntegerOption(o => o.setName('item_id').setDescription('ID предмета').setRequired(true)).addIntegerOption(o => o.setName('quantity').setDescription('Количество').setMinValue(1).setRequired(true)).addIntegerOption(o => o.setName('price').setDescription('Цена').setMinValue(1).setRequired(true)), command('auction-list', 'Список аукциона'), command('auction-buy', 'Купить лот').addIntegerOption(o => o.setName('id').setDescription('ID лота').setRequired(true)), command('reputation', 'Поблагодарить участника').addUserOption(o => o.setName('user').setDescription('Участник').setRequired(true))];
const client = new Client({ intents: [GatewayIntentBits.Guilds, GatewayIntentBits.GuildMessages, GatewayIntentBits.GuildVoiceStates] });
commands.push(command('twenty-one', 'Сыграть в 21 против бота').addIntegerOption(o => o.setName('bet').setDescription('Размер ставки').setMinValue(1).setRequired(true)));
const redNumbers = new Set([1, 3, 5, 7, 9, 12, 14, 16, 18, 19, 21, 23, 25, 27, 30, 32, 34, 36]); const rouletteColor = number => number === 0 ? 'зеро' : redNumbers.has(number) ? 'красное' : 'чёрное';
const achievementNames = { first_game: 'Первая игра', high_roller: 'Крупная ставка', first_purchase: 'Первая покупка', daily_week: 'Неделя наград', level_five: 'Пятый уровень' };
const addItem = (userId, itemId, quantity) => inventory().updateOne({ user_id: userId, item_id: itemId }, { $inc: { quantity }, $setOnInsert: { _id: `${userId}:${itemId}`, user_id: userId, item_id: itemId } }, { upsert: true });
async function checkAchievements(userId) { const user = await users().findOne({ _id: userId }); const [games] = await gameStats().aggregate([{ $match: { user_id: userId } }, { $group: { _id: null, total: { $sum: '$played' }, wagered: { $max: '$wagered' } } }]); const [owned] = await inventory().aggregate([{ $match: { user_id: userId } }, { $group: { _id: null, total: { $sum: '$quantity' } } }]); const unlocked = []; for (const [code, condition] of Object.entries({ first_game: (games?.total || 0) >= 1, high_roller: (games?.wagered || 0) >= 1000, first_purchase: (owned?.total || 0) >= 1, daily_week: user.daily_streak >= 7, level_five: user.level >= 5 })) if (condition && await unlockAchievement(userId, code)) unlocked.push(achievementNames[code]); return unlocked; }
async function gameResult(user, game, bet, payout, text) { const result = await users().updateOne({ _id: user.id, balance: { $gte: bet } }, { $inc: { balance: payout - bet } }); if (!result.modifiedCount) throw new Error('Ставка больше твоего баланса.'); await recordGame(user.id, game, bet, payout); if (payout > bet) await addXp(user.id, 15); const player = await users().findOne({ _id: user.id }); const unlocked = await checkAchievements(user.id); return `${text}\nБаланс: **${player.balance.toLocaleString()} ✦**${unlocked.length ? `\n🏆 Достижение: **${unlocked.join(', ')}**` : ''}`; }
const rarity = item => ` · ${item.rarity || 'common'}${item.type === 'case' ? ' · кейс' : ''}`;
async function ownedItems(userId) { return inventory().aggregate([{ $match: { user_id: userId, quantity: { $gt: 0 } } }, { $lookup: { from: 'items', localField: 'item_id', foreignField: 'id', as: 'item' } }, { $unwind: '$item' }, { $project: { item_id: 1, name: '$item.name', icon: '$item.icon', rarity: '$item.rarity', type: '$item.type', quantity: 1 } }]); }
const buttons = list => list.length ? list.reduce((rows, button, index) => { if (index % 5 === 0) rows.push(new ActionRowBuilder()); rows[rows.length - 1].addComponents(button); return rows; }, []) : [];
const rouletteSessions = new Map();
const twentyOneSessions = new Map();
const twentyOneDeck = () => Array.from({ length: 4 }, () => ['A', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K']).flat().sort(() => Math.random() - 0.5);
const twentyOneValue = cards => { let total = cards.reduce((sum, card) => sum + (card === 'A' ? 11 : ['J', 'Q', 'K'].includes(card) ? 10 : Number(card)), 0), aces = cards.filter(card => card === 'A').length; while (total > 21 && aces--) total -= 10; return total; };
const takeTwentyOneCard = session => session.deck.pop();
function createTwentyOneSession(owner, bet) { const session = { owner, bet, deck: twentyOneDeck(), player: [], bot: [] }; session.player.push(takeTwentyOneCard(session), takeTwentyOneCard(session)); session.bot.push(takeTwentyOneCard(session), takeTwentyOneCard(session)); const id = Math.random().toString(36).slice(2, 10); twentyOneSessions.set(id, session); return id; }
function twentyOneScreen(id, session, result = '') { const playerScore = twentyOneValue(session.player), botScore = twentyOneValue(session.bot), finished = Boolean(result); return { content: `🃏 **21 (очко)**\nСтавка: **${session.bet.toLocaleString()} ✦**\n\nТы: **${session.player.join(' · ')}** = **${playerScore}**\nБот: **${finished ? session.bot.join(' · ') : `${session.bot[0]} · ?`}**${finished ? ` = **${botScore}**` : ''}${result ? `\n\n${result}` : '\n\nДобери карту или остановись.'}`, components: [new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`t:21:${session.owner}:${id}:hit`).setLabel('Взять карту').setStyle(ButtonStyle.Primary).setDisabled(finished), new ButtonBuilder().setCustomId(`t:21:${session.owner}:${id}:stand`).setLabel('Хватит').setStyle(ButtonStyle.Secondary).setDisabled(finished), new ButtonBuilder().setCustomId(`t:21:${session.owner}:${id}:again`).setLabel('Новая игра').setStyle(ButtonStyle.Success).setDisabled(!finished))] }; }
const createRouletteSession = (owner, bet) => {
  const id = Math.random().toString(36).slice(2, 10);
  rouletteSessions.set(id, { owner, bet, numbers: new Set(), page: 0 });
  return id;
};
async function rouletteText(balance, session, extra = 'Выбери одно или несколько чисел.') { const history = await collections.roulette_history.find({}, { sort: { id: -1 }, limit: 10, projection: { _id: 0, number: 1, color: 1 } }); const selected = [...session.numbers].sort((a, b) => a - b); const total = session.bet * selected.length; return `${history.length ? `Последние игры: ${history.map(game => `${game.number} ${game.color === 'красное' ? '🔴' : game.color === 'чёрное' ? '⚫' : '🟢'}`).join(' · ')}\n` : 'Последних игр пока нет.\n'}\n🎰 **Рулетка**\nСтавка на число: **${session.bet.toLocaleString()} ✦** · Баланс: **${balance.toLocaleString()} ✦**\nВыбрано: ${selected.length ? `**${selected.join(', ')}**` : 'ничего'} · Итоговая ставка: **${total.toLocaleString()} ✦**\n${extra}`; }
function rouletteRows(owner, id) { const session = rouletteSessions.get(id); const numbers = Array.from({ length: 37 }, (_, n) => n).slice(session.page * 15, session.page * 15 + 15); const rows = buttons(numbers.map(n => new ButtonBuilder().setCustomId(`r:n:${owner}:${id}:${n}`).setLabel(String(n)).setStyle(session.numbers.has(n) ? ButtonStyle.Success : n === 0 ? ButtonStyle.Primary : redNumbers.has(n) ? ButtonStyle.Danger : ButtonStyle.Secondary))); rows.push(new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`r:p:${owner}:${id}:${(session.page + 2) % 3}`).setLabel('Назад').setStyle(ButtonStyle.Primary), new ButtonBuilder().setCustomId(`r:run:${owner}:${id}`).setLabel(`Играть (${session.numbers.size})`).setStyle(ButtonStyle.Success).setDisabled(!session.numbers.size), new ButtonBuilder().setCustomId(`r:b:${owner}:${id}`).setLabel('Изменить ставку').setStyle(ButtonStyle.Secondary), new ButtonBuilder().setCustomId(`r:p:${owner}:${id}:${(session.page + 1) % 3}`).setLabel('Далее').setStyle(ButtonStyle.Primary))); return rows; }
function gameRows(game, owner, bet, initial = false) { const row = new ActionRowBuilder(); if (game === 'coin' && initial) { row.addComponents(new ButtonBuilder().setCustomId(`g:${game}:${owner}:${bet}:heads`).setLabel('Орёл').setStyle(ButtonStyle.Primary), new ButtonBuilder().setCustomId(`g:${game}:${owner}:${bet}:tails`).setLabel('Решка').setStyle(ButtonStyle.Secondary)); } else row.addComponents(new ButtonBuilder().setCustomId(`g:${game}:${owner}:${bet}:${game === 'dice' ? 'roll' : game === 'slots' ? 'spin' : 'again'}`).setLabel(initial ? (game === 'dice' ? 'Бросить' : 'Крутить') : 'Играть снова').setStyle(ButtonStyle.Primary)); row.addComponents(new ButtonBuilder().setCustomId(`g:b:${owner}:${bet}:${game}`).setLabel('Изменить ставку').setStyle(ButtonStyle.Success)); return [row]; }
const gameIntro = (game, bet) => `${game === 'coin' ? '🪙 **Монетка**: выбери сторону.' : game === 'dice' ? '🎲 **Кости**: 4-6 дают 2x.' : '🎰 **Слоты**: пара 2x, три одинаковых 4x, три 7 - 10x.'}\nСтавка: **${bet.toLocaleString()} ✦**`;
async function menuScreen(owner, screen) { const user = await users().findOne({ _id: owner }); const nav = new ActionRowBuilder().addComponents(['games', 'inventory', 'shop', 'sell', 'achievements'].map(name => new ButtonBuilder().setCustomId(`m:${owner}:${name}`).setLabel({ games: 'Игры', inventory: 'Инвентарь', shop: 'Магазин', sell: 'Продать', achievements: 'Достижения' }[name]).setStyle(name === screen ? ButtonStyle.Primary : ButtonStyle.Secondary))); if (screen === 'games') return { content: `**Игры**\nБаланс: **${user.balance.toLocaleString()} ✦**\nСтартовая ставка: 100 ✦.`, components: [nav, new ActionRowBuilder().addComponents(['coin', 'dice', 'slots', 'roulette'].map(game => new ButtonBuilder().setCustomId(`m:${owner}:game:${game}`).setLabel({ coin: 'Монетка', dice: 'Кости', slots: 'Слоты', roulette: 'Рулетка' }[game]).setStyle(ButtonStyle.Success)))] }; if (screen === 'inventory' || screen === 'sell') { const owned = await ownedItems(owner); const content = `**${screen === 'sell' ? 'Продажа' : 'Инвентарь'}**\n${owned.length ? owned.map(i => `${i.icon} **#${i.item_id} ${i.name}** ×${i.quantity}${rarity(i)}`).join('\n') : 'Инвентарь пуст.'}`; const actions = screen === 'sell' ? buttons(owned.slice(0, 20).map(i => new ButtonBuilder().setCustomId(`m:${owner}:sell:${i.item_id}`).setLabel(`Продать #${i.item_id}`).setStyle(ButtonStyle.Danger))) : []; return { content, components: [nav, ...actions] }; } if (screen === 'shop') { const shop = await items().find({ active: 1 }, { sort: { id: 1 } }); return { content: `**Магазин**\n${shop.length ? shop.map(i => `**#${i.id} ${i.icon} ${i.name}** - ${i.price.toLocaleString()} ✦${rarity(i)}${i.stock >= 0 ? ` · осталось ${i.stock}` : ''}\n${i.description}`).join('\n\n') : 'Магазин пуст.'}`, components: [nav, ...buttons(shop.slice(0, 20).map(i => new ButtonBuilder().setCustomId(`m:${owner}:buy:${i.id}`).setLabel(`Купить #${i.id}`).setStyle(ButtonStyle.Success)))] }; } const unlocked = await achievements().find({ user_id: owner }); const dates = new Map(unlocked.map(row => [row.code, row.unlocked_at])); return { content: `**Достижения**\n${Object.entries(achievementNames).map(([code, name]) => `${dates.has(code) ? '🔓' : '🔒'} **${name}**${dates.has(code) ? ` - ${new Date(dates.get(code)).toLocaleDateString('ru-RU')}` : ''}`).join('\n')}`, components: [nav] }; }

client.once('ready', async () => { console.log(`Discord: ${client.user.tag}`); if (process.env.CLIENT_ID && process.env.GUILD_ID) await new REST({ version: '10' }).setToken(process.env.DISCORD_TOKEN).put(Routes.applicationGuildCommands(process.env.CLIENT_ID, process.env.GUILD_ID), { body: commands }); });
client.on('interactionCreate', async interaction => { try {
  if (!getDbStatus().connected) return interaction.isRepliable() ? interaction.reply({ content: 'База данных пока недоступна. Попробуй ещё раз через 30 секунд.', ephemeral: true }) : null;
  if (interaction.isButton()) { const p = interaction.customId.split(':'); const owner = p[0] === 'm' ? p[1] : p[0] === 't' ? p[2] : p[2]; if (!owner || owner !== interaction.user.id) return interaction.reply({ content: 'Это меню создано другим игроком.', ephemeral: true }); const player = await ensureUser(owner, interaction.user.username);
    if (p[0] === 't') { const [, game, , id, action] = p, session = twentyOneSessions.get(id); if (game !== '21' || !session || session.owner !== owner) return interaction.reply({ content: 'Раунд истёк. Начни новую игру.', ephemeral: true }); if (action === 'again') { if (player.balance < session.bet) return interaction.reply({ content: 'Ставка больше твоего баланса.', ephemeral: true }); const nextId = createTwentyOneSession(owner, session.bet); return interaction.update(twentyOneScreen(nextId, twentyOneSessions.get(nextId))); } if (action === 'hit') { session.player.push(takeTwentyOneCard(session)); if (twentyOneValue(session.player) <= 21) return interaction.update(twentyOneScreen(id, session)); }
      while (twentyOneValue(session.bot) < 17) session.bot.push(takeTwentyOneCard(session)); const playerScore = twentyOneValue(session.player), botScore = twentyOneValue(session.bot); const won = playerScore <= 21 && (botScore > 21 || playerScore > botScore), draw = playerScore <= 21 && playerScore === botScore, payout = won ? session.bet * 2 : draw ? session.bet : 0; const outcome = playerScore > 21 ? `Перебор: **${playerScore}**. Потеряно: **${session.bet.toLocaleString()} ✦**` : botScore > 21 ? `У бота перебор. Выигрыш: **${payout.toLocaleString()} ✦**` : draw ? `Ничья. Ставка **${session.bet.toLocaleString()} ✦** возвращена.` : won ? `Ты выиграл у бота. Выигрыш: **${payout.toLocaleString()} ✦**` : `Бот выиграл. Потеряно: **${session.bet.toLocaleString()} ✦**`; const result = await gameResult(player, 'twenty-one', session.bet, payout, outcome); return interaction.update(twentyOneScreen(id, session, result)); }
    if (p[0] === 'r') { const [, action, , id, value] = p; const session = rouletteSessions.get(id); if (!session || session.owner !== owner) return interaction.reply({ content: 'Раунд истёк. Открой новую рулетку.', ephemeral: true }); if (action === 'n') { const number = Number(value); session.numbers.has(number) ? session.numbers.delete(number) : session.numbers.add(number); return interaction.update({ content: await rouletteText(player.balance, session), components: rouletteRows(owner, id) }); } if (action === 'p') { session.page = Number(value); return interaction.update({ content: await rouletteText(player.balance, session), components: rouletteRows(owner, id) }); } if (action === 'b') return interaction.showModal(new ModalBuilder().setCustomId(`b:${owner}:roulette:${id}`).setTitle('Изменить ставку на число').addComponents(new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('bet').setLabel('Сумма на каждое число').setStyle(TextInputStyle.Short).setValue(String(session.bet)).setRequired(true)))); if (action !== 'run' || !session.numbers.size) return; const totalBet = session.bet * session.numbers.size; if (player.balance < totalBet) return interaction.reply({ content: `Для всех чисел нужно **${totalBet.toLocaleString()} ✦**.`, ephemeral: true }); const result = Math.floor(Math.random() * 37), color = rouletteColor(result), won = session.numbers.has(result), payout = won ? session.bet * 36 : 0; await collections.roulette_history.insertOne({ number: result, color, created_at: Date.now() }); const resultText = await gameResult(player, 'roulette', totalBet, payout, `Выпало **${result}** - ${color}.\n${won ? `🎉 Выигрыш за число ${result}: **${payout.toLocaleString()} ✦**` : `Потеряно: **${totalBet.toLocaleString()} ✦**`}`); const updated = await users().findOne({ _id: owner }); const nextId = createRouletteSession(owner, session.bet); return interaction.update({ content: await rouletteText(updated.balance, rouletteSessions.get(nextId), `${resultText}\n\nВыбери числа для следующего раунда.`), components: rouletteRows(owner, nextId) }); }
    if (p[0] === 'g') { const [, game, , betText, action] = p; const bet = Number(betText); if (game === 'b') return interaction.showModal(new ModalBuilder().setCustomId(`b:${owner}:${action}:0`).setTitle('Изменить ставку').addComponents(new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('bet').setLabel('Сумма ставки').setStyle(TextInputStyle.Short).setValue(String(bet)).setRequired(true)))); if (game === 'coin' && action === 'again') return interaction.update({ content: gameIntro(game, bet), components: gameRows(game, owner, bet, true) }); if (player.balance < bet) return interaction.reply({ content: 'Ставка больше твоего баланса.', ephemeral: true }); let text, payout; if (game === 'coin') { const result = Math.random() < .5 ? 'heads' : 'tails', won = action === result; payout = won ? bet * 2 : 0; text = `🪙 Выпало **${result === 'heads' ? 'орёл' : 'решка'}**. ${won ? `Выигрыш: **${payout.toLocaleString()} ✦**` : `Потеряно: **${bet.toLocaleString()} ✦**`}`; } else if (game === 'dice') { const roll = Math.floor(Math.random() * 6) + 1; payout = roll >= 4 ? bet * 2 : 0; text = `🎲 Выпало **${roll}**. ${payout ? `Выигрыш: **${payout.toLocaleString()} ✦**` : `Потеряно: **${bet.toLocaleString()} ✦**`}`; } else { const symbols = ['🍒', '🍋', '💎', '7️⃣'], result = Array.from({ length: 3 }, () => symbols[Math.floor(Math.random() * symbols.length)]); payout = result[0] === result[1] && result[1] === result[2] ? bet * (result[0] === '7️⃣' ? 10 : 4) : new Set(result).size < 3 ? bet * 2 : 0; text = `🎰 ${result.join(' | ')}\n${payout ? `Выигрыш: **${payout.toLocaleString()} ✦**` : `Потеряно: **${bet.toLocaleString()} ✦**`}`; } return interaction.update({ content: await gameResult(player, game, bet, payout, text), components: gameRows(game, owner, bet) }); }
    if (p[0] === 'm') { const screen = p[3] || p[2]; if (p[2] === 'game') { const game = p[3], bet = 100; if (player.balance < bet) return interaction.reply({ content: 'Для ставки 100 ✦ недостаточно монет.', ephemeral: true }); if (game === 'roulette') { const id = createRouletteSession(owner, bet); return interaction.update({ content: await rouletteText(player.balance, rouletteSessions.get(id)), components: rouletteRows(owner, id) }); } return interaction.update({ content: gameIntro(game, bet), components: gameRows(game, owner, bet, true) }); } if (p[2] === 'buy') { await buyItem(player, Number(p[3])); return interaction.update(await menuScreen(owner, 'shop')); } if (p[2] === 'sell') { await sellItem(player, Number(p[3]), 1); return interaction.update(await menuScreen(owner, 'sell')); } return interaction.update(await menuScreen(owner, screen)); }
  }
  if (interaction.isModalSubmit() && interaction.customId.startsWith('b:')) { const [, owner, game, page] = interaction.customId.split(':'); if (owner !== interaction.user.id) return interaction.reply({ content: 'Это меню создано другим игроком.', ephemeral: true }); const bet = Number(interaction.fields.getTextInputValue('bet')), player = await ensureUser(owner, interaction.user.username); if (!Number.isInteger(bet) || bet < 1 || player.balance < bet) return interaction.reply({ content: 'Укажи целую ставку, не превышающую баланс.', ephemeral: true }); if (game === 'roulette') { const session = rouletteSessions.get(page); if (!session) return interaction.reply({ content: 'Раунд истёк. Открой новую рулетку.', ephemeral: true }); session.bet = bet; return interaction.update({ content: await rouletteText(player.balance, session), components: rouletteRows(owner, page) }); } return interaction.update({ content: gameIntro(game, bet), components: gameRows(game, owner, bet, true) }); }
  if (!interaction.isChatInputCommand()) return; await interaction.deferReply(); interaction.reply = payload => interaction.editReply(typeof payload === 'string' ? payload : (({ ephemeral, ...message }) => message)(payload)); const user = await ensureUser(interaction.user.id, interaction.user.username), name = interaction.commandName;
  if (name === 'balance') return interaction.reply(`**${user.username}**\nБаланс: **${user.balance.toLocaleString()} ✦**\nУровень: **${user.level}** · XP: ${user.xp % 500}/500`);
  if (name === 'menu') return interaction.reply(await menuScreen(user.id, 'games'));
  if (name === 'achievements') { const member = interaction.options.getUser('user') || interaction.user, rows = await achievements().find({ user_id: member.id }); const dates = new Map(rows.map(row => [row.code, row.unlocked_at])); return interaction.reply(`**Достижения ${member.username}**\n${Object.entries(achievementNames).map(([code, label]) => `${dates.has(code) ? '🔓' : '🔒'} **${label}**${dates.has(code) ? ` - ${new Date(dates.get(code)).toLocaleString('ru-RU')}` : ''}`).join('\n')}`); }
  if (name === 'roulette') { const bet = interaction.options.getInteger('bet'); if (user.balance < bet) return interaction.reply({ content: 'Ставка больше твоего баланса.', ephemeral: true }); const id = createRouletteSession(user.id, bet); return interaction.reply({ content: await rouletteText(user.balance, rouletteSessions.get(id), 'Выбери числа. Каждое выбранное число получает отдельную ставку и выплачивается 36x.'), components: rouletteRows(user.id, id) }); }
  if (name === 'twenty-one') { const bet = interaction.options.getInteger('bet'); if (user.balance < bet) return interaction.reply({ content: 'Ставка больше твоего баланса.', ephemeral: true }); const id = createTwentyOneSession(user.id, bet); return interaction.reply(twentyOneScreen(id, twentyOneSessions.get(id))); }
  if (['coin', 'dice', 'slots'].includes(name)) { const bet = interaction.options.getInteger('bet'); if (user.balance < bet) return interaction.reply({ content: 'Ставка больше твоего баланса.', ephemeral: true }); return interaction.reply({ content: gameIntro(name, bet), components: gameRows(name, user.id, bet, true) }); }
  if (name === 'open-case') { const itemId = interaction.options.getInteger('item_id'), item = await items().findOne({ id: itemId, type: 'case' }); if (!item || !(item.caseDrops || []).length) return interaction.reply({ content: 'Кейс не найден или не настроен.', ephemeral: true }); const consumed = await inventory().updateOne({ user_id: user.id, item_id: itemId, quantity: { $gte: 1 } }, { $inc: { quantity: -1 } }); if (!consumed.modifiedCount) return interaction.reply({ content: 'У тебя нет этого кейса.', ephemeral: true }); const total = item.caseDrops.reduce((sum, drop) => sum + drop.weight, 0); let roll = Math.random() * total; const drop = item.caseDrops.find(entry => (roll -= entry.weight) < 0) || item.caseDrops.at(-1); const prize = await items().findOne({ id: drop.itemId }); if (!prize) { await addItem(user.id, itemId, 1); throw new Error('Дроп кейса больше не существует. Кейс возвращён.'); } await addItem(user.id, prize.id, drop.quantity); await logAudit('case_open', user.id, drop.quantity, `Кейс #${itemId}, предмет #${prize.id}`); return interaction.reply(`▣ Открыт **${item.name}**: ${prize.icon} **${prize.name}** ×${drop.quantity}${rarity(prize)}.`); }
  if (name === 'shop') { const shop = await items().find({ active: 1 }); return interaction.reply(shop.length ? shop.map(i => `**#${i.id} ${i.icon} ${i.name}** - ${i.price.toLocaleString()} ✦${rarity(i)}${i.stock >= 0 ? ` · осталось ${i.stock}` : ''}\n${i.description}`).join('\n\n') : 'Магазин пуст.'); }
  if (name === 'inventory') { const owned = await ownedItems(user.id); return interaction.reply(owned.length ? owned.map(i => `${i.icon} **#${i.item_id} ${i.name}** ×${i.quantity}${rarity(i)}`).join('\n') : 'Инвентарь пуст.'); }
  if (name === 'buy') return interaction.reply(await buyItem(user, interaction.options.getInteger('item_id')));
  if (name === 'sell') return interaction.reply(await sellItem(user, interaction.options.getInteger('item_id'), interaction.options.getInteger('quantity')));
  if (name === 'profile') { const member = interaction.options.getUser('user') || interaction.user, profile = await ensureUser(member.id, member.username), [games] = await gameStats().aggregate([{ $match: { user_id: profile.id } }, { $group: { _id: null, played: { $sum: '$played' }, wagered: { $sum: '$wagered' }, payout: { $sum: '$payout' } } }]); return interaction.reply(`**Профиль ${member.username}**\nБаланс: **${profile.balance.toLocaleString()} ✦** · Уровень: **${profile.level}**\nИгры: ${games?.played || 0} · Поставлено: ${(games?.wagered || 0).toLocaleString()} ✦`); }
  if (name === 'daily' || name === 'weekly') { const weekly = name === 'weekly', last = weekly ? user.last_weekly : user.last_daily, period = weekly ? 604800000 : 86400000; if (Date.now() - last < period) return interaction.reply({ content: 'Награда уже получена.', ephemeral: true }); const streak = weekly ? null : Date.now() - last < 172800000 ? user.daily_streak + 1 : 1, reward = weekly ? 1500 + user.level * 100 : 250 + user.level * 50 + Math.min(streak, 7) * 25; await users().updateOne({ _id: user.id }, { $inc: { balance: reward }, $set: weekly ? { last_weekly: Date.now() } : { last_daily: Date.now(), daily_streak: streak } }); await addXp(user.id, weekly ? 100 : 50); const unlocked = weekly ? [] : await checkAchievements(user.id); return interaction.reply(`Награда: **+${reward.toLocaleString()} ✦**.${unlocked.length ? `\n🏆 ${unlocked.join(', ')}` : ''}`); }
  if (name === 'capitalization') { const [coins] = await users().aggregate([{ $group: { _id: null, total: { $sum: '$balance' } } }]); const [owned] = await inventory().aggregate([{ $lookup: { from: 'items', localField: 'item_id', foreignField: 'id', as: 'item' } }, { $unwind: '$item' }, { $group: { _id: null, total: { $sum: { $multiply: ['$quantity', '$item.price'] } } } }]); return interaction.reply(`**Капитализация сервера**\nМонеты на балансах: **${(coins?.total || 0).toLocaleString()} ✦**\nСтоимость предметов: **${(owned?.total || 0).toLocaleString()} ✦**\nИтого: **${((coins?.total || 0) + (owned?.total || 0)).toLocaleString()} ✦**`); }
  if (name === 'transfer') { const target = interaction.options.getUser('user'), amount = interaction.options.getInteger('amount'); if (target.bot || target.id === user.id || user.balance < amount) return interaction.reply({ content: 'Перевод невозможен.', ephemeral: true }); await ensureUser(target.id, target.username); const sent = await users().updateOne({ _id: user.id, balance: { $gte: amount } }, { $inc: { balance: -amount } }); if (!sent.modifiedCount) return interaction.reply({ content: 'Недостаточно монет.', ephemeral: true }); await users().updateOne({ _id: target.id }, { $inc: { balance: amount } }); return interaction.reply(`Передано **${amount.toLocaleString()} ✦** пользователю **${target.username}**.`); }
  if (name === 'leaderboard') { const type = interaction.options.getString('type') || 'balance'; const rows = type === 'games' ? await gameStats().aggregate([{ $group: { _id: '$user_id', value: { $sum: '$played' } } }, { $lookup: { from: 'users', localField: '_id', foreignField: '_id', as: 'user' } }, { $unwind: '$user' }, { $project: { _id: 0, username: '$user.username', value: 1 } }, { $sort: { value: -1, username: 1 } }, { $limit: 10 }]) : await users().find({}, { sort: { [type]: -1, username: 1 }, limit: 10, projection: { _id: 0, username: 1, [type]: 1 } }); if (type !== 'games') rows.forEach(row => { row.value = row[type]; }); return interaction.reply(`**Топ: ${type === 'games' ? 'Количество игр' : type === 'level' ? 'Уровень' : 'Баланс'}**\n${rows.map((row, index) => `${index + 1}. **${row.username}** - ${Number(row.value).toLocaleString()}${type === 'balance' ? ' ✦' : ''}`).join('\n') || 'Пока пусто.'}`); }
  if (name === 'promo') { const code = interaction.options.getString('code').trim().toUpperCase(), promo = await promos().findOne({ _id: code, active: 1 }); if (!promo || promo.uses >= promo.max_uses || (promo.expires_at && promo.expires_at < Date.now())) return interaction.reply({ content: 'Промокод недействителен.', ephemeral: true }); try { await claims().insertOne({ _id: `${code}:${user.id}`, code, user_id: user.id, claimed_at: Date.now() }); } catch (error) { if (error.code === 11000) return interaction.reply({ content: 'Ты уже активировал этот промокод.', ephemeral: true }); throw error; } const used = await promos().updateOne({ _id: code, uses: { $lt: promo.max_uses } }, { $inc: { uses: 1 } }); if (!used.modifiedCount) return interaction.reply({ content: 'Промокод недействителен.', ephemeral: true }); await users().updateOne({ _id: user.id }, { $inc: { balance: promo.reward } }); await logAudit('promo_claim', user.id, promo.reward, code); return interaction.reply(`Промокод **${code}** активирован: **+${promo.reward.toLocaleString()} ✦**.`); }
  if (name === 'reputation') { const target = interaction.options.getUser('user'); if (target.bot || target.id === user.id || Date.now() - user.last_reputation < 86400000) return interaction.reply({ content: 'Благодарность недоступна.', ephemeral: true }); await ensureUser(target.id, target.username); await users().updateOne({ _id: user.id }, { $set: { last_reputation: Date.now() } }); await users().updateOne({ _id: target.id }, { $inc: { balance: 25 } }); await logAudit('reputation', user.id, 25, `Получатель ${target.id}`); return interaction.reply(`**${target.username}** получает **+25 ✦** за благодарность.`); }
  if (name === 'auction-list') { const lots = await auctions().aggregate([{ $match: { active: 1 } }, { $sort: { id: -1 } }, { $limit: 20 }, { $lookup: { from: 'items', localField: 'item_id', foreignField: 'id', as: 'item' } }, { $lookup: { from: 'users', localField: 'seller_id', foreignField: '_id', as: 'seller' } }, { $unwind: '$item' }, { $unwind: '$seller' }]); return interaction.reply(lots.length ? `**Аукцион**\n${lots.map(lot => `#${lot.id} ${lot.item.icon} **${lot.item.name}** ×${lot.quantity} - **${lot.price.toLocaleString()} ✦** · ${lot.seller.username}`).join('\n')}` : 'Активных лотов нет.'); }
  if (name === 'auction-create') { const itemId = interaction.options.getInteger('item_id'), quantity = interaction.options.getInteger('quantity'), price = interaction.options.getInteger('price'), item = await items().findOne({ id: itemId }); const removed = item && await inventory().updateOne({ user_id: user.id, item_id: itemId, quantity: { $gte: quantity } }, { $inc: { quantity: -quantity } }); if (!removed?.modifiedCount) return interaction.reply({ content: 'У тебя нет такого количества предметов.', ephemeral: true }); await auctions().insertOne({ seller_id: user.id, item_id: itemId, quantity, price, active: 1, created_at: Date.now() }); return interaction.reply(`Предмет **${item.name}** выставлен на аукцион.`); }
  if (name === 'auction-buy') { const id = interaction.options.getInteger('id'), lot = await auctions().findOne({ id, active: 1 }); if (!lot || lot.seller_id === user.id) return interaction.reply({ content: 'Лот недоступен.', ephemeral: true }); const paid = await users().updateOne({ _id: user.id, balance: { $gte: lot.price } }, { $inc: { balance: -lot.price } }); if (!paid.modifiedCount) return interaction.reply({ content: 'Недостаточно монет.', ephemeral: true }); const claimed = await auctions().updateOne({ id, active: 1 }, { $set: { active: 0 } }); if (!claimed.modifiedCount) { await users().updateOne({ _id: user.id }, { $inc: { balance: lot.price } }); return interaction.reply({ content: 'Лот уже куплен.', ephemeral: true }); } await users().updateOne({ _id: lot.seller_id }, { $inc: { balance: lot.price } }); await addItem(user.id, lot.item_id, lot.quantity); return interaction.reply(`Лот **#${id}** куплен за **${lot.price.toLocaleString()} ✦**.`); }
} catch (error) { console.error('Interaction failed:', error); if (interaction.isRepliable() && !interaction.replied) interaction.deferred ? interaction.editReply('Произошла ошибка. Попробуй ещё раз.') : interaction.reply({ content: 'Произошла ошибка. Попробуй ещё раз.', ephemeral: true }); } });
async function buyItem(user, itemId) { const item = await items().findOne({ id: itemId, active: 1 }); if (!item || item.stock === 0) throw new Error('Предмет недоступен.'); const charged = await users().updateOne({ _id: user.id, balance: { $gte: item.price } }, { $inc: { balance: -item.price } }); if (!charged.modifiedCount) throw new Error('Недостаточно монет.'); if (item.stock > 0) { const reserved = await items().updateOne({ id: item.id, stock: { $gt: 0 } }, { $inc: { stock: -1 } }); if (!reserved.modifiedCount) { await users().updateOne({ _id: user.id }, { $inc: { balance: item.price } }); throw new Error('Предмет закончился.'); } } await addItem(user.id, item.id, 1); await addXp(user.id, 15); await logAudit('shop_purchase', user.id, item.price, `Предмет #${item.id}`); const unlocked = await checkAchievements(user.id); return `Куплено: ${item.icon} **${item.name}** за ${item.price.toLocaleString()} ✦.${unlocked.length ? `\n🏆 ${unlocked.join(', ')}` : ''}`; }
async function sellItem(user, itemId, quantity) { const item = await items().findOne({ id: itemId }); if (!item) throw new Error('Предмет не найден.'); const removed = await inventory().updateOne({ user_id: user.id, item_id: itemId, quantity: { $gte: quantity } }, { $inc: { quantity: -quantity } }); if (!removed.modifiedCount) throw new Error('У тебя нет такого количества предметов.'); const reward = Math.floor(item.price * quantity * 0.5); await users().updateOne({ _id: user.id }, { $inc: { balance: reward } }); await logAudit('item_sell', user.id, reward, `Предмет #${itemId} x${quantity}`); return `Продано: ${item.icon} **${item.name}** ×${quantity} за **${reward.toLocaleString()} ✦**.`; }
client.on('messageCreate', async message => { if (message.author.bot || !message.guild || !getDbStatus().connected) return; const user = await ensureUser(message.author.id, message.author.username); if (Date.now() - user.last_message_reward < 60000) return; await users().updateOne({ _id: user.id }, { $inc: { balance: 5 }, $set: { last_message_reward: Date.now() } }); await addXp(user.id, 10); });
function connectMongoWithRetry() { connectDb().then(() => console.log('MongoDB connected')).catch(error => { console.error('MongoDB connection failed, retrying in 30 seconds:', error.message); setTimeout(connectMongoWithRetry, 30000); }); }
function start() { app.listen(port, () => console.log(`Admin panel: http://localhost:${port}`)); connectMongoWithRetry(); if (process.env.DISCORD_TOKEN) client.login(process.env.DISCORD_TOKEN).catch(error => console.error('Discord login failed:', error.message)); }
start();
